
BIN = bin

run: build
	./$(BIN)/main.exe code.rcy
	./code_rcy.exe

nobuild:
	./$(BIN)/main.exe code.rcy
	./code_rcy.exe

build: $(BIN) build_lexparse
	g++ -g -mavx2 -march=native -std=c++17 -Wno-register tree.cpp generated/lex.yy.c generated/parser.tab.cpp preprocessor.cpp codegen.cpp main.cpp -o $(BIN)/main.exe

build_lexparse:
	win_bison -d parser.y -o generated/parser.tab.cpp
	win_flex -o generated/lex.yy.c lexer.l

$(BIN):
	mkdir bin